<?php require __DIR__.'/app/core.php'; $page=$_GET['page']??'home'; $valid=['home','hizmetler','paketler','referanslar','blog','haberler','iletisim','kvkk','gizlilik','cerez']; if(!in_array($page,$valid,true)){$page='home';} $s=site_settings(); header_html($page); ?>
<?php if($page==='home'): $posts=array_slice(posts_all(),0,3); $refs=array_values(array_filter(references_all(),fn($r)=>!empty($r['active']))); ?>
<section class="hero-xl" id="merhaba">
  <div class="hero-copy"><span class="eyebrow"><?=e($s['hero_badge'])?></span><h1><?=e($s['hero_title'])?></h1><p><?=e($s['hero_desc'])?></p><div class="hero-actions"><a class="btn primary" href="/iletisim">Teklif Al</a><a class="btn ghost" href="/hizmetler">Hizmetleri İncele</a><a class="btn text" href="/referanslar">Referanslar</a></div></div>
  <div class="orbit-card"><div class="orb orb1"></div><div class="orb orb2"></div><div class="panel-card"><b>Dijital işlerinizde sonuç alın.</b><p>Google’da görünmeyen, mobilde güven vermeyen ve WhatsApp’a yönlendirmeyen site müşteri kaçırır.</p><ul><li>SEO temeli</li><li>Mobil performans</li><li>WhatsApp / arama dönüşümü</li><li>Blog, haber, referans yönetimi</li></ul></div></div>
</section>
<section class="stats"><article><b>4.999 TL</b><span>Başlangıç web sitesi</span></article><article><b>1 yıl</b><span>Sözleşmeli hizmet yapısı</span></article><article><b>SEO</b><span>Teknik kurulum ve içerik planı</span></article><article><b>CRM</b><span>Teklif, sözleşme, takip</span></article></section>
<section class="section split"><div><span class="eyebrow">Biz kimiz?</span><h2>Web sitesi olmayan işletmeleri hızlıca dijital vitrine taşıyan yazılım ajansıyız.</h2></div><p>Küçük işletmeler, servis firmaları, güzellik salonları, sanayi üreticileri ve yerel hizmet veren markalar için hızlı açılan, güven veren, WhatsApp’a müşteri taşıyan siteler yapıyoruz. Gerektiğinde randevu, yönetim paneli, çok dil, reklam ve e-ticaret danışmanlığı ekliyoruz.</p></section>
<section class="section services-preview"><div class="section-head"><span class="eyebrow">Neler yapıyoruz?</span><h2>Tek sayfa siteden özel yazılıma kadar net paketler.</h2></div><div class="service-grid"><?php foreach(service_groups() as $g): ?><article><i><?=e($g['icon'])?></i><h3><?=e($g['title'])?></h3><ul><?php foreach($g['items'] as $it): ?><li><?=e($it)?></li><?php endforeach; ?></ul></article><?php endforeach; ?></div></section>
<section class="section darkline"><div><span class="eyebrow">Kimler için?</span><h2>Web sitesi olmayan ama telefondan müşteri alan her işletme için.</h2></div><div class="chips"><?php foreach(sector_targets() as $t): ?><span><?=e($t)?></span><?php endforeach; ?></div></section>
<section class="section works"><div class="section-head"><span class="eyebrow">Neler yaptık?</span><h2>Referanslar ve aktif çalışmalar.</h2><a href="/referanslar">Tümünü gör</a></div><div class="work-grid"><?php foreach(array_slice($refs,0,6) as $r): ?><article><div class="work-logo"><?php if(!empty($r['logo'])): ?><img src="<?=e($r['logo'])?>" alt="<?=e($r['name'])?> logo"><?php else: ?><?=e(first_letter($r['name']))?><?php endif; ?></div><h3><?=e($r['name'])?></h3><p><?=e($r['note']??'Web çalışması')?></p><small><?=e($r['category']??'Web Tasarım')?></small></article><?php endforeach; ?></div></section>
<section class="section journal"><div class="section-head"><span class="eyebrow">Neler yazdık?</span><h2>SEO ve web sitesi rehberleri.</h2><a href="/blog">Blog’a git</a></div><div class="post-cards"><?php foreach($posts as $p): ?><article><small><?=e($p['created_at']??'')?></small><h3><a href="/<?=($p['type']??'blog')==='haber'?'haber':'blog'?>/<?=e($p['slug'])?>"><?=e($p['title'])?></a></h3><p><?=e($p['summary'])?></p></article><?php endforeach; ?></div></section>
<section class="section cta-band"><h2><?=e($s['cta_title'])?></h2><p><?=e($s['cta_desc'])?></p><a class="btn primary" href="/iletisim">WhatsApp’tan Teklif Al</a></section>
<?php elseif($page==='hizmetler'): ?>
<section class="page-hero"><span class="eyebrow">Neler Yapıyoruz?</span><h1>Web tasarım, yazılım, SEO, reklam ve e-ticaret danışmanlığı.</h1><p>İşletmenin ihtiyacına göre gereksiz masraf çıkarmadan doğru dijital paketi kuruyoruz.</p></section><section class="section"><div class="service-grid wide"><?php foreach(service_groups() as $g): ?><article><i><?=e($g['icon'])?></i><h2><?=e($g['title'])?></h2><ul><?php foreach($g['items'] as $it): ?><li><?=e($it)?></li><?php endforeach; ?></ul></article><?php endforeach; ?></div></section>
<section class="section process"><h2>Nasıl ilerliyoruz?</h2><div class="timeline"><article><b>01</b><h3>İhtiyaç analizi</h3><p>Sektör, rakip, hedef müşteri ve paket ihtiyacı netleştirilir.</p></article><article><b>02</b><h3>Teklif ve sözleşme</h3><p>Fiyat, kapsam, domain/hosting ve teslim süreci yazılı hale gelir.</p></article><article><b>03</b><h3>Tasarım ve kurulum</h3><p>Mobil uyumlu yapı, SEO temeli, WhatsApp ve iletişim akışı hazırlanır.</p></article><article><b>04</b><h3>Yayın ve takip</h3><p>Yayına alınır, müşteri takip linki ve yenileme takibi oluşturulur.</p></article></div></section>
<?php elseif($page==='paketler'): ?>
<section class="page-hero"><span class="eyebrow">Paketler</span><h1>Başlangıçtan yönetim panelli profesyonel siteye kadar paketler.</h1><p>Başlangıç fiyatı tek sayfalık HTML web sitesi içindir. Randevu, çok sayfa, panel ve çok dil ihtiyaca göre tekliflendirilir.</p></section><section class="section pricing"><article><b>Başlangıç</b><h2>Tek Sayfa HTML</h2><p class="price">4.999 TL’den başlar</p><ul><li>Mobil uyumlu tasarım</li><li>WhatsApp ve arama butonu</li><li>SEO temel kurulum</li><li>Harita ve iletişim alanı</li></ul></article><article><b>Randevulu</b><h2>Tek Sayfa + Randevu</h2><p class="price">Teklif alınır</p><ul><li>Talep/randevu formu</li><li>Hizmet alanları</li><li>KVKK sayfaları</li><li>WhatsApp takip</li></ul></article><article><b>Kurumsal</b><h2>Çok Sayfalı Site</h2><p class="price">Teklif alınır</p><ul><li>Hizmet sayfaları</li><li>Blog/haber altyapısı</li><li>Referans yönetimi</li><li>Çok dil opsiyonu</li></ul></article><article><b>Panel</b><h2>Yönetim Panelli Site</h2><p class="price">Teklif alınır</p><ul><li>İçerik yönetimi</li><li>Blog/haber/referans ekleme</li><li>Randevu opsiyonu</li><li>Sipariş takip sistemi</li></ul></article></section>
<?php elseif($page==='referanslar'): $refs=array_values(array_filter(references_all(),fn($r)=>!empty($r['active']))); ?>
<section class="page-hero"><span class="eyebrow">Neler Yaptık?</span><h1>Referanslarımız ve çalışma alanlarımız.</h1><p>Admin panelden referans ismi, logosu, web site adresi ve aktif/pasif durumu yönetilebilir.</p></section><section class="section"><div class="filter-pills"><span>Tümü</span><span>Web Tasarım</span><span>SEO</span><span>E-Ticaret</span><span>Randevu</span><span>Yazılım</span></div><div class="work-grid big"><?php foreach($refs as $r): ?><article><div class="work-logo"><?php if(!empty($r['logo'])): ?><img src="<?=e($r['logo'])?>" alt="<?=e($r['name'])?> logo"><?php else: ?><?=e(first_letter($r['name']))?><?php endif; ?></div><h2><?=e($r['name'])?></h2><p><?=e($r['note']??'Web sitesi çalışması')?></p><small><?=e($r['category']??'Web Tasarım')?></small><?php if(!empty($r['website'])): ?><a href="<?=e($r['website'])?>" target="_blank" rel="noopener">Web sitesini ziyaret et</a><?php endif; ?></article><?php endforeach; ?></div><?php if(!$refs): ?><p>Aktif referans henüz yayınlanmadı.</p><?php endif; ?></section>
<?php elseif($page==='blog'||$page==='haberler'): $type=$page==='blog'?'blog':'haber'; $posts=array_values(array_filter(posts_all(),fn($p)=>($p['type']??'blog')===$type)); ?>
<section class="page-hero"><span class="eyebrow"><?= $page==='blog'?'Neler Yazdık?':'Haberler' ?></span><h1><?= $page==='blog'?'Web sitesi, SEO ve dijital büyüme yazıları.':'Xtanbul duyuruları ve gelişmeler.' ?></h1></section><section class="section"><div class="post-cards listing"><?php foreach($posts as $p): ?><article><small><?=e($p['created_at']??'')?></small><h2><a href="/<?= $type==='blog'?'blog':'haber' ?>/<?=e($p['slug'])?>"><?=e($p['title'])?></a></h2><p><?=e($p['summary'])?></p><a href="/<?= $type==='blog'?'blog':'haber' ?>/<?=e($p['slug'])?>">Devamını oku</a></article><?php endforeach; ?></div></section>
<?php elseif($page==='iletisim'): $wa=normalize_whatsapp($s['contact_whatsapp']); ?>
<section class="page-hero"><span class="eyebrow">Bize Ulaşın</span><h1>Web sitesi teklifi almak için yazın.</h1><p>Sektörünüzü, istediğiniz paket türünü ve varsa örnek beğendiğiniz siteleri gönderin; size net teklif çıkaralım.</p></section><section class="section contact-grid"><article><h2>WhatsApp / Telefon</h2><p><a href="tel:<?=e($s['contact_phone'])?>"><?=e($s['contact_phone'])?></a></p><a class="btn primary" href="https://wa.me/<?=$wa?>?text=Merhaba%2C%20web%20sitesi%20teklifi%20almak%20istiyorum." target="_blank" rel="noopener">WhatsApp’tan Yaz</a></article><article><h2>E-posta</h2><p><a href="mailto:<?=e($s['contact_email'])?>"><?=e($s['contact_email'])?></a></p><p>Teklif, sözleşme, domain/hosting ve proje takip süreçleri için yazabilirsiniz.</p></article><article><h2>Adres</h2><p><?=e($s['contact_address'])?></p><a class="btn ghost" href="<?=e($s['maps_url'])?>" target="_blank" rel="noopener">Haritada Aç</a></article></section>
<?php elseif($page==='kvkk'): ?><section class="page-hero"><span class="eyebrow">KVKK</span><h1>KVKK Aydınlatma Metni</h1></section><section class="section article"><p>Bu metin, Xtanbul Yazılım Agent ile iletişim kuran ziyaretçilerin ve müşterilerin kişisel verilerinin hangi amaçlarla işlendiğini açıklamak için hazırlanmıştır.</p><h2>İşlenen Veriler</h2><p>Ad soyad, telefon, e-posta, firma adı, web sitesi ihtiyacı, teklif ve sözleşme süreçlerinde paylaşılan bilgiler işlenebilir.</p><h2>İşleme Amaçları</h2><p>Teklif hazırlama, iletişim kurma, hizmet sunumu, ödeme ve sözleşme süreçlerini yürütme, müşteri ilişkilerini takip etme ve yasal yükümlülükleri yerine getirme amaçlarıyla veri işlenebilir.</p><h2>Aktarım</h2><p>Veriler; hizmetin yürütülmesi için zorunlu olduğu ölçüde hosting, alan adı, ödeme, muhasebe ve teknik altyapı hizmet sağlayıcılarıyla paylaşılabilir.</p><h2>Haklarınız</h2><p>KVKK kapsamındaki başvuru, düzeltme, silme, itiraz ve bilgi talebi haklarınız için iletişim sayfasındaki kanallardan bize ulaşabilirsiniz.</p><p><b>Not:</b> Bu metin teknik taslaktır; nihai hukuki metin şirket unvanı, vergi bilgileri ve veri işleme süreçlerine göre özelleştirilmelidir.</p></section>
<?php elseif($page==='gizlilik'): ?><section class="page-hero"><span class="eyebrow">Gizlilik</span><h1>Gizlilik Politikası</h1></section><section class="section article"><p>Ziyaretçi ve müşteri bilgileri, yalnızca teklif, iletişim, hizmet sunumu ve yasal yükümlülüklerin yerine getirilmesi amacıyla kullanılır. Bilgiler yetkisiz üçüncü kişilerle paylaşılmaz.</p></section>
<?php elseif($page==='cerez'): ?><section class="page-hero"><span class="eyebrow">Çerez</span><h1>Çerez Politikası</h1></section><section class="section article"><p>Site deneyimini iyileştirmek, güvenlik ve performans sağlamak amacıyla zorunlu çerezler kullanılabilir. Reklam/analitik çerezleri eklenirse kullanıcı bilgilendirmesi ayrıca güncellenmelidir.</p></section>
<?php endif; ?>
<?php footer_html(); ?>
