<?php
require __DIR__ . '/app/core.php';
require_login();
$id = (int)($_GET['id'] ?? 0);
$lead = $id ? get_lead($id) : null;
if (!$lead) { http_response_code(404); echo 'Teklif bulunamadı'; exit; }
$packages = package_catalog();
$selected = (string)($lead['package_type'] ?? 'onepage');
$selectedPackage = $packages[$selected] ?? $packages['onepage'];
$price = (string)(($lead['package_price'] ?? '') ?: $selectedPackage['price']);
$features = sector_competitor_features((string)($lead['sector'] ?? ''), (string)($lead['sub_sector'] ?? ''));
?>
<!doctype html>
<html lang="tr"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Teklif - <?=e($lead['name'] ?? '')?></title>
<style>
body{font-family:Arial,Helvetica,sans-serif;background:#0b1020;color:#101828;margin:0;padding:24px}.paper{max-width:900px;margin:auto;background:#fff;border-radius:24px;overflow:hidden;box-shadow:0 20px 60px rgba(0,0,0,.25)}.hero{background:linear-gradient(135deg,#151b3f,#2d6cdf,#8b5cf6);color:#fff;padding:34px}.hero h1{margin:0 0 8px;font-size:34px}.hero p{margin:0;opacity:.9}.content{padding:32px}.grid{display:grid;grid-template-columns:1fr 1fr;gap:18px}.box{border:1px solid #e5e7eb;border-radius:16px;padding:18px;background:#f8fafc}.box h3{margin:0 0 10px}.price{font-size:30px;font-weight:800;color:#111827}.packages{display:grid;grid-template-columns:repeat(2,1fr);gap:12px;margin-top:14px}.pkg{border:1px solid #e5e7eb;border-radius:14px;padding:14px}.pkg.active{border-color:#2563eb;background:#eff6ff}.muted{color:#667085}.actions{padding:0 32px 32px;display:flex;gap:12px}.btn{appearance:none;border:0;border-radius:12px;background:#2563eb;color:#fff;padding:12px 18px;font-weight:700;cursor:pointer}.ghost{background:#f3f4f6;color:#111827}@media(max-width:720px){body{padding:0}.paper{border-radius:0}.grid,.packages{grid-template-columns:1fr}.hero h1{font-size:26px}}@media print{body{background:#fff;padding:0}.paper{box-shadow:none;border-radius:0}.actions{display:none}}
</style></head><body><main class="paper"><section class="hero"><h1>Web Site Teklifi</h1><p><?=e($lead['name'] ?? '')?> için hazırlanan ön teklif</p></section><section class="content"><div class="grid"><div class="box"><h3>Firma Bilgisi</h3><p><b>İşletme:</b> <?=e($lead['name'] ?? '')?></p><p><b>Sektör:</b> <?=e(trim(($lead['sector'] ?? '').' / '.($lead['sub_sector'] ?? ''), ' /'))?></p><p><b>Bölge:</b> <?=e(trim(($lead['district'] ?? '').' / '.($lead['city'] ?? ''), ' /'))?></p><p><b>Telefon:</b> <?=e($lead['phone'] ?? '')?></p></div><div class="box"><h3>Önerilen Paket</h3><p><b><?=e($selectedPackage['label'])?></b></p><p class="muted"><?=e($selectedPackage['desc'])?></p><div class="price"><?=e($price)?></div><p class="muted">Başlangıç teklifi tek sayfalık HTML site için 4.999 TL’den başlar; üst paketler ihtiyaca göre netleştirilir.</p></div></div><div class="box" style="margin-top:18px"><h3>Rakiplerde Öne Çıkan Özellikler</h3><p><?=e($lead['sub_sector'] ?? 'Bu sektör')?> tarafında güçlü rakip sitelerinde genelde şu alanlar öne çıkar:</p><ul><?php foreach($features as $f): ?><li><?=e($f)?></li><?php endforeach; ?></ul></div><h2>Paket Seçenekleri</h2><div class="packages"><?php foreach($packages as $key=>$p): ?><div class="pkg <?=$key===$selected?'active':''?>"><b><?=e($p['label'])?></b><p class="muted"><?=e($p['desc'])?></p><strong><?=e($p['price'])?></strong></div><?php endforeach; ?></div><div class="box" style="margin-top:18px"><h3>Ek Hizmetler</h3><p>Profesyonel reklam danışmanlığı, e-ticaret danışmanlığı, sosyal medya danışmanlığı ve çok dilli web site kurulumu da yapılır.</p></div></section><div class="actions"><button class="btn" onclick="window.print()">PDF olarak yazdır/kaydet</button><a class="btn ghost" href="index.php">Panele dön</a></div></main></body></html>
